/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import ObjetsSimples.Statut;
import exceptions.DataExceptions;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import xchange.Xchange;

/**
 *
 * @author cda210
 */
public class EditAuteurJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditAuteurJFrame
     */
    String imagePth = null;
    public EditAuteurJFrame() {
        initComponents();
        IDjTextField.setVisible(false);
    }
    
    private HomePage MotherJFrame;

    public HomePage getMotherJFrame() {
        return MotherJFrame;
    }

    public void setMotherJFrame(HomePage MotherJFrame) {
        this.MotherJFrame = MotherJFrame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDjTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        StatusjComboBox = new javax.swing.JComboBox();
        lastNamejLabel = new javax.swing.JLabel();
        firstNamejLabel = new javax.swing.JLabel();
        biojLabel = new javax.swing.JLabel();
        picturejLabel = new javax.swing.JLabel();
        notesjLabel = new javax.swing.JLabel();
        lastNamejTextField = new javax.swing.JTextField();
        firstNamejTextField = new javax.swing.JTextField();
        biojScrollPane = new javax.swing.JScrollPane();
        biojTextArea = new javax.swing.JTextArea();
        notesjScrollPane = new javax.swing.JScrollPane();
        notesjTextArea = new javax.swing.JTextArea();
        imagejLabel = new javax.swing.JLabel();
        editjButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();
        BrowsejButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        IDjTextField.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifier Auteur");

        jPanel1.setToolTipText("");

        StatusjComboBox.setModel(initModelStatus());

        lastNamejLabel.setText("Nom* :");

        firstNamejLabel.setText("Prénom* :");

        biojLabel.setText("Biographie :");

        picturejLabel.setText("Image :");

        notesjLabel.setText("Commentaires :");

        biojTextArea.setColumns(20);
        biojTextArea.setLineWrap(true);
        biojTextArea.setRows(5);
        biojTextArea.setWrapStyleWord(true);
        biojScrollPane.setViewportView(biojTextArea);

        notesjTextArea.setColumns(20);
        notesjTextArea.setLineWrap(true);
        notesjTextArea.setRows(5);
        notesjTextArea.setWrapStyleWord(true);
        notesjScrollPane.setViewportView(notesjTextArea);

        imagejLabel.setBackground(new java.awt.Color(255, 255, 255));

        editjButton.setText("Modifier");
        editjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButtonActionPerformed(evt);
            }
        });

        canceljButton.setText("Annuler");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });

        BrowsejButton.setText("Parcourir");
        BrowsejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowsejButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("* Champs obligatoires");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(editjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(canceljButton))
                    .addComponent(StatusjComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNamejLabel)
                            .addComponent(firstNamejLabel)
                            .addComponent(biojLabel))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNamejTextField)
                            .addComponent(firstNamejTextField)
                            .addComponent(biojScrollPane))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notesjLabel)
                            .addComponent(picturejLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BrowsejButton)
                                .addGap(18, 18, 18)
                                .addComponent(imagejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(notesjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(StatusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNamejLabel)
                    .addComponent(lastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNamejLabel)
                    .addComponent(firstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(biojLabel)
                    .addComponent(biojScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notesjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notesjLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BrowsejButton)
                    .addComponent(picturejLabel)
                    .addComponent(imagejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(canceljButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButtonActionPerformed
        // TODO add your handling code here:
        Pattern p01 = Pattern.compile("[- 'À-ȳ-a-zA-Z]{1,100}");
        Matcher m01 = p01.matcher(lastNamejTextField.getText());
        Matcher m02 = p01.matcher(firstNamejTextField.getText());

        if (m01.matches() && m02.matches()) {

            Xchange xch = new Xchange();
            xch.connect();

            PreparedStatement ps;

            try {
                String query = "UPDATE AUTEUR "
                + "SET STATUSID = ?, AUTHORLASTNAME = ?, AUTHORFIRSTNAME = ?, AUTHORBIO = ?, AUTHORPICTURE = ?, AUTHORNOTES = ? "
                + "WHERE AUTHORID = ?";
                ps = xch.getConnexion().prepareStatement(query);
                Statut status = (Statut) StatusjComboBox.getSelectedItem();
                ps.setString(1, status.getId().toString());
                ps.setString(2, lastNamejTextField.getText());
                ps.setString(3, firstNamejTextField.getText());
                ps.setString(4, biojTextArea.getText());
                if (imagePth == null)
                ps.setNull(5, java.sql.Types.BLOB);
                else {
                    InputStream img = new FileInputStream(new File(imagePth));
                    ps.setBlob(5, img);
                }
                ps.setString(6, notesjTextArea.getText());
                ps.setString(7, IDjTextField.getText());

                if (ps.executeUpdate() != 0){
                    JOptionPane.showMessageDialog(null, "Auteur modifié");
                    MotherJFrame.refreshTable();
                    this.dispose();
                    xch.close();

                } else {
                    JOptionPane.showMessageDialog(null, "Erreur");
                    xch.close();
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Champ(s) vide(s) ou caractères non valides", "Erreur de saisie", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_editjButtonActionPerformed
    
    private ImageIcon resizePic(String picPath){
        ImageIcon myImg = new ImageIcon(picPath);
        Image img = myImg.getImage().getScaledInstance(imagejLabel.getWidth(), imagejLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon myPic = new ImageIcon(img);
        return myPic;  
    }
    
    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_canceljButtonActionPerformed

    private void BrowsejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowsejButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser filec = new JFileChooser();
        filec.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter(".jpg .png .gif", "jpg","png","gif");
        filec.addChoosableFileFilter(fileFilter);

        int fileState = filec.showSaveDialog(null);

        if(fileState == JFileChooser.APPROVE_OPTION){
            File selectedFile = filec.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            imagePth = path;
            //            picturejLabel.setIcon(new ImageIcon(path));
            imagejLabel.setIcon(resizePic(path));
        } else if (fileState == JFileChooser.CANCEL_OPTION){
            System.out.println("");
        }
    }//GEN-LAST:event_BrowsejButtonActionPerformed
    
    private DefaultComboBoxModel initModelStatus(){
        return new DefaultComboBoxModel(initVectorStatus());
    }
    
    private Vector initVectorStatus(){
        Vector v = new Vector();
        Xchange xch = new Xchange();
        xch.connect();
               
        try {
            String query = "SELECT STATUSID, STATUSNAME, STATUS_DESCR FROM STATUS WHERE STATUSID BETWEEN 500 AND 598";
            Statement s = xch.getConnexion().createStatement();
            ResultSet rs = s.executeQuery(query);
            
            while (rs.next()){
                Statut status = new Statut();
                try {
                    status.setId(rs.getString("STATUSID"));
                    status.setStatusname(rs.getString("STATUSNAME"));
                    status.setStatusdescr(rs.getString("STATUS_DESCR"));
                } catch (DataExceptions ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }                
                v.add(status);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        xch.close();
        return v;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAuteurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAuteurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAuteurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAuteurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAuteurJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowsejButton;
    public javax.swing.JTextField IDjTextField;
    public javax.swing.JComboBox StatusjComboBox;
    private javax.swing.JLabel biojLabel;
    private javax.swing.JScrollPane biojScrollPane;
    public javax.swing.JTextArea biojTextArea;
    private javax.swing.JButton canceljButton;
    private javax.swing.JButton editjButton;
    private javax.swing.JLabel firstNamejLabel;
    public javax.swing.JTextField firstNamejTextField;
    public javax.swing.JLabel imagejLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNamejLabel;
    public javax.swing.JTextField lastNamejTextField;
    private javax.swing.JLabel notesjLabel;
    private javax.swing.JScrollPane notesjScrollPane;
    public javax.swing.JTextArea notesjTextArea;
    private javax.swing.JLabel picturejLabel;
    // End of variables declaration//GEN-END:variables
}
