/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import ObjetsSimples.*;
import exceptions.DataExceptions;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

import xchange.Xchange;

/**
 *
 * @author cda201
 */
public class JFLigneMod extends javax.swing.JFrame {

    private JFCommandeMod jfMere;
    private Commande commande;
    private Client client;

    /**
     * Creates new form JFLigneMod
     */
    public JFLigneMod() {
        initComponents();

    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public Commande getCommande() {
        return commande;
    }

    public void setCommande(Commande commande) {
        this.commande = commande;
    }

    public JFrame getJfMere() {
        return jfMere;
    }

    public void setJfMere(JFCommandeMod jfMere) {
        this.jfMere = jfMere;
    }

    private DefaultComboBoxModel initLivre() {
        Vector v = new Vector();

        Xchange ech = new Xchange();
        Statement stat = null;
        String query = "SELECT BOOKISBN13,BOOKTITLE,BOOKPRICE, BOOKAVAILABLESTOCK FROM LIVRE WHERE STATUSID != 499";
        ResultSet rs = null;

        try {

            ech.connect();
            stat = ech.getConnexion().createStatement();
            rs = stat.executeQuery(query);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Création connexion Livre: " + ex.getErrorCode() + " / " + ex.getMessage(), "LigneCMDMod", JOptionPane.ERROR_MESSAGE);;
        }
        try {
            while (rs.next()) {
                Livre livre;
                livre = new Livre() {
                    @Override
                    public String toString() {
                        return getIsbn13() + " : " + getTitle() + " : " + getPrice() + " €, Stock : " + getAvailableStock();
                    }
                };
                livre.setIsbn13(rs.getString("BOOKISBN13"));
                livre.setPrice(rs.getString("BOOKPRICE"));
                livre.setTitle(rs.getString("BOOKTITLE"));
                livre.setAvailableStock(rs.getString("BOOKAVAILABLESTOCK"));

                v.add(livre);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Lecture données Livre : " + ex.getErrorCode() + " / " + ex.getMessage(), "LigneCMDMod", JOptionPane.ERROR_MESSAGE);
        } catch (DataExceptions ex) {
            JOptionPane.showMessageDialog(null, "Lecture données Livre : " + ex.getErrorCode() + " / " + ex.getMessage(), "LigneCMDMod", JOptionPane.ERROR_MESSAGE);
        } finally {
            ech.close();
        }

        return new DefaultComboBoxModel(v);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbLivre = new javax.swing.JComboBox();
        jbValider = new javax.swing.JButton();
        jbFermer = new javax.swing.JButton();
        jsQuantite = new javax.swing.JSpinner();
        jlPrixTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel7.setText("Choissisiez la quantité");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Prix Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Choississez un livre");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jcbLivre.setModel(initLivre());

        jbValider.setText("Valider");
        jbValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbValiderActionPerformed(evt);
            }
        });

        jbFermer.setText("Fermer");
        jbFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFermerActionPerformed(evt);
            }
        });

        jsQuantite.setFocusable(false);
        jsQuantite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsQuantiteStateChanged(evt);
            }
        });

        jlPrixTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlPrixTotal.setText("0 €");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jcbLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jsQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlPrixTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jbValider)
                .addGap(142, 142, 142)
                .addComponent(jbFermer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcbLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jsQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jlPrixTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbValider)
                    .addComponent(jbFermer))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsQuantiteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsQuantiteStateChanged

        int qt = (Integer) jsQuantite.getValue();
        Livre livre = (Livre) jcbLivre.getSelectedItem();

        int qtLim = Integer.parseInt(livre.getAvailableStock());
        if (qtLim < qt) {
            JOptionPane.showMessageDialog(rootPane, "Le stock disponible n'est pas suffisant", "Stock", JOptionPane.INFORMATION_MESSAGE);
        } else {

            float prixTot = qt * Float.parseFloat(livre.getPrice());
            prixTot = prixTot * 100;
            prixTot = Math.round(prixTot);
            prixTot = prixTot / 100;
            jlPrixTotal.setText(prixTot + " €");
        }
    }//GEN-LAST:event_jsQuantiteStateChanged

    private void jbFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbFermerActionPerformed

    private void jbValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbValiderActionPerformed

        LigneCmd ligne = new LigneCmd();
        ligne.setClient(client);
        ligne.setCommande(commande);
        System.out.println("ID commande = " + commande.getID());
        Livre livre = (Livre) jcbLivre.getSelectedItem();
        ligne.setLivre(livre);
        int qt = (Integer) jsQuantite.getValue();
        int error = 0;
        try {
            ligne.setQuantite(String.valueOf(qt));
        } catch (DataExceptions ex) {
            JOptionPane.showMessageDialog(rootPane, "CréationLigneCmd :" + ex.getMessage(), "Ligne de Commande", JOptionPane.INFORMATION_MESSAGE);
            error += 1;
        }
        try {
            ligne.setTva("5.5");
        } catch (DataExceptions ex) {
            JOptionPane.showMessageDialog(rootPane, "CréationLigneCmd :" + ex.getMessage(), "Ligne de Commande", JOptionPane.INFORMATION_MESSAGE);
            error += 1;
        }
        try {
            ligne.setPrixHT(livre.getPrice());
        } catch (DataExceptions ex) {
            JOptionPane.showMessageDialog(rootPane, "CréationLigneCmd :" + ex.getMessage(), "Ligne de Commande", JOptionPane.INFORMATION_MESSAGE);
            error += 1;
        }

        if (error == 0) {
            Xchange ech = new Xchange();
            ech.connect();
            ligne.save(ech, ligne.genValue());
            ech.close();
            jfMere.refresh();

        }

        this.dispose();

    }//GEN-LAST:event_jbValiderActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLigneMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLigneMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLigneMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLigneMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLigneMod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbFermer;
    private javax.swing.JButton jbValider;
    private javax.swing.JComboBox jcbLivre;
    private javax.swing.JLabel jlPrixTotal;
    private javax.swing.JSpinner jsQuantite;
    // End of variables declaration//GEN-END:variables
}
