package Interface;

import exceptions.DataExceptions;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import pwdUtils.PwdUtils;
import xchange.Xchange;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cda210
 */
public class NewAccountJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewAccountJFrame
     */
    public NewAccountJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlejPanel = new javax.swing.JPanel();
        titlejLabel = new javax.swing.JLabel();
        loginjPanel = new javax.swing.JPanel();
        lastNamejLabel = new javax.swing.JLabel();
        firstNamejLabel = new javax.swing.JLabel();
        usernamejLabel = new javax.swing.JLabel();
        passwordjLabel = new javax.swing.JLabel();
        lastNamejTextField = new javax.swing.JTextField();
        firstNamejTextField = new javax.swing.JTextField();
        usernamejTextField = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        confirmjButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nouveau compte");

        titlejPanel.setBackground(new java.awt.Color(0, 102, 153));
        titlejPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 153)));

        titlejLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        titlejLabel.setForeground(new java.awt.Color(255, 255, 255));
        titlejLabel.setText("MA LIBRAIRIE");

        javax.swing.GroupLayout titlejPanelLayout = new javax.swing.GroupLayout(titlejPanel);
        titlejPanel.setLayout(titlejPanelLayout);
        titlejPanelLayout.setHorizontalGroup(
            titlejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlejPanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(titlejLabel)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        titlejPanelLayout.setVerticalGroup(
            titlejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlejPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titlejLabel)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lastNamejLabel.setText("Nom :");

        firstNamejLabel.setText("Prénom :");

        usernamejLabel.setText("Nom d'utilisateur :");

        passwordjLabel.setText("Mot de passe :");

        confirmjButton.setText("Valider");
        confirmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmjButtonActionPerformed(evt);
            }
        });

        canceljButton.setText("Annuler");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginjPanelLayout = new javax.swing.GroupLayout(loginjPanel);
        loginjPanel.setLayout(loginjPanelLayout);
        loginjPanelLayout.setHorizontalGroup(
            loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginjPanelLayout.createSequentialGroup()
                .addGroup(loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginjPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(loginjPanelLayout.createSequentialGroup()
                                .addGroup(loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNamejLabel)
                                    .addComponent(firstNamejLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(loginjPanelLayout.createSequentialGroup()
                                .addGroup(loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernamejLabel)
                                    .addComponent(passwordjLabel))
                                .addGap(18, 18, 18)
                                .addGroup(loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernamejTextField)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(confirmjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(canceljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        loginjPanelLayout.setVerticalGroup(
            loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginjPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNamejLabel)
                    .addComponent(lastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNamejLabel)
                    .addComponent(firstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamejLabel)
                    .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordjLabel)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canceljButton)
                    .addComponent(confirmjButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(loginjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmjButtonActionPerformed
        // TODO add your handling code here:
        Pattern p01 = Pattern.compile("[- 'À-ȳ-a-zA-Z]{1,100}");
        Pattern p02 = Pattern.compile("[-'À-ȳ-a-zA-Z0-9]{1,150}");
        Pattern p03 = Pattern.compile("[!@#\\$%\\^&-'À-ȳ-a-zA-Z0-9]{1,150}");
        Matcher m01 = p01.matcher(lastNamejTextField.getText());
        Matcher m02 = p01.matcher(firstNamejTextField.getText());
        Matcher m03 = p02.matcher(usernamejTextField.getText());
        Matcher m04 = p03.matcher(String.valueOf(jPasswordField.getPassword()));

        if (m01.matches() && m02.matches() && m03.matches() && m04.matches()) {

            Xchange xch = new Xchange();
            xch.connect();
            String salt = "OOJ8TJVQcDB/0Byx2PvZrVKCxJ4pdHJNzKeNnwrK";
            String pw = PwdUtils.hashPassword(String.valueOf(jPasswordField.getPassword()), salt).toString();
            System.out.println(pw);

            PreparedStatement ps;

            try {
                String query = "INSERT INTO EMPLOYES "
                             + "(STATUSID, EMPLASTNAME, EMPFIRSTNAME, EMPLOGIN, EMPPASSWORD )"
                             + " VALUES "
                             + "(?, ?, ?, ?, ? )";
                ps = xch.getConnexion().prepareStatement(query);
                ps.setString(1, "1000");
                ps.setString(2, lastNamejTextField.getText());
                ps.setString(3, firstNamejTextField.getText());
                ps.setString(4, usernamejTextField.getText());
                ps.setString(5, pw);
                
                if (takenName(usernamejTextField.getText())){
                    JOptionPane.showMessageDialog(null, "Nom d'utilisateur existant");
                } else {
                    if (ps.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "Nouveau compte créé");
                    } else {
                        JOptionPane.showMessageDialog(null, "Erreur");
                }
                  
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

            xch.close();

        } else {
            JOptionPane.showMessageDialog(null, "Champ(s) vide(s) ou caractères non valides", "Erreur de saisie", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_confirmjButtonActionPerformed

    private boolean takenName (String name){
        boolean takenName = false;
        Xchange xch = new Xchange();
        xch.connect();
        PreparedStatement ps;
        
        try {
            ps = xch.getConnexion().prepareStatement("SELECT * FROM EMPLOYES where EMPLOGIN = ?");
            ps.setString(1, usernamejTextField.getText());
            ResultSet rs;
            rs = ps.executeQuery();

            if (rs.next())
                takenName = true;

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

        xch.close();
        
        return takenName;
    }

    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginJDialog ljd = new LoginJDialog(this, true);
        ljd.setVisible(true);
    }//GEN-LAST:event_canceljButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAccountJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canceljButton;
    private javax.swing.JButton confirmjButton;
    private javax.swing.JLabel firstNamejLabel;
    private javax.swing.JTextField firstNamejTextField;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel lastNamejLabel;
    private javax.swing.JTextField lastNamejTextField;
    private javax.swing.JPanel loginjPanel;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JLabel titlejLabel;
    private javax.swing.JPanel titlejPanel;
    private javax.swing.JLabel usernamejLabel;
    private javax.swing.JTextField usernamejTextField;
    // End of variables declaration//GEN-END:variables
}
